import "./globals.css";
import { PDFProvider } from '@/context/pdf-context/PDFContext';

const generateMetadata = () => {
    return {
        title: "Create Next App",
        description: "Generated by create next app",
    };
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
            <link
                href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap"
                rel="stylesheet"
            />
        </head>
        <body>
        <PDFProvider>
            {children}
        </PDFProvider>
        </body>
        </html>
    );
}