import "./globals.css";


const generateMetadata = () => {
    return {
        title: "Create Next App",
        description: "Generated by create next app",
    };
}

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <head>
            <link rel="preconnect" href="https://fonts.googleapis.com" />
            <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin="anonymous" />
            <link
                href="https://fonts.googleapis.com/css2?family=DM+Sans:wght@400;700&display=swap"
                rel="stylesheet"
            />
            <link
                rel="prefetch"
                href="/assets/font/Google-Sans/GoogleSans-Regular.ttf"
                as="font"
                type="font/ttf"
                crossOrigin="anonymous"
            />
        </head>
        <body>
        {children}
        </body>
        </html>
    );
}